# Generated by Django 5.1.3 on 2024-11-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
